//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVC___remake.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_In_Vmin {
            get {
                return ((ushort)(this["setting_In_Vmin"]));
            }
            set {
                this["setting_In_Vmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_In_Vmax {
            get {
                return ((ushort)(this["setting_In_Vmax"]));
            }
            set {
                this["setting_In_Vmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_In_Imax {
            get {
                return ((ushort)(this["setting_In_Imax"]));
            }
            set {
                this["setting_In_Imax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_DC_Vref {
            get {
                return ((ushort)(this["setting_DC_Vref"]));
            }
            set {
                this["setting_DC_Vref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_DC_Vmin {
            get {
                return ((ushort)(this["setting_DC_Vmin"]));
            }
            set {
                this["setting_DC_Vmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_DC_Vmax {
            get {
                return ((ushort)(this["setting_DC_Vmax"]));
            }
            set {
                this["setting_DC_Vmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_Out_Vload {
            get {
                return ((ushort)(this["setting_Out_Vload"]));
            }
            set {
                this["setting_Out_Vload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort setting_Out_Imax {
            get {
                return ((ushort)(this["setting_Out_Imax"]));
            }
            set {
                this["setting_Out_Imax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime setting_DateTime {
            get {
                return ((global::System.DateTime)(this["setting_DateTime"]));
            }
            set {
                this["setting_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Input_Va {
            get {
                return ((float)(this["main_Input_Va"]));
            }
            set {
                this["main_Input_Va"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Input_Vb {
            get {
                return ((float)(this["main_Input_Vb"]));
            }
            set {
                this["main_Input_Vb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Input_Vc {
            get {
                return ((float)(this["main_Input_Vc"]));
            }
            set {
                this["main_Input_Vc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_DC_link {
            get {
                return ((float)(this["main_DC_link"]));
            }
            set {
                this["main_DC_link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Freq {
            get {
                return ((float)(this["main_Freq"]));
            }
            set {
                this["main_Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Output_Va {
            get {
                return ((float)(this["main_Output_Va"]));
            }
            set {
                this["main_Output_Va"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Output_Vb {
            get {
                return ((float)(this["main_Output_Vb"]));
            }
            set {
                this["main_Output_Vb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Output_Vc {
            get {
                return ((float)(this["main_Output_Vc"]));
            }
            set {
                this["main_Output_Vc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Output_Ia {
            get {
                return ((float)(this["main_Output_Ia"]));
            }
            set {
                this["main_Output_Ia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Output_Ib {
            get {
                return ((float)(this["main_Output_Ib"]));
            }
            set {
                this["main_Output_Ib"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float main_Output_Ic {
            get {
                return ((float)(this["main_Output_Ic"]));
            }
            set {
                this["main_Output_Ic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime main_DateTime {
            get {
                return ((global::System.DateTime)(this["main_DateTime"]));
            }
            set {
                this["main_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int settings_Reset {
            get {
                return ((int)(this["settings_Reset"]));
            }
            set {
                this["settings_Reset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort page_num {
            get {
                return ((ushort)(this["page_num"]));
            }
            set {
                this["page_num"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Set_second {
            get {
                return ((ushort)(this["Set_second"]));
            }
            set {
                this["Set_second"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Set_minute {
            get {
                return ((ushort)(this["Set_minute"]));
            }
            set {
                this["Set_minute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Set_date {
            get {
                return ((ushort)(this["Set_date"]));
            }
            set {
                this["Set_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Set_month {
            get {
                return ((ushort)(this["Set_month"]));
            }
            set {
                this["Set_month"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Set_year {
            get {
                return ((ushort)(this["Set_year"]));
            }
            set {
                this["Set_year"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Set_hour {
            get {
                return ((ushort)(this["Set_hour"]));
            }
            set {
                this["Set_hour"] = value;
            }
        }
    }
}
